title: "Ductwork Docs"
email: support@getductwork.io
description: A Ruby Pipeline Framework
baseurl: ""
url: "https://docs.getductwork.io"
github_username: zoso10

remote_theme: just-the-docs/just-the-docs
color_scheme: dark
plugins:
  - jekyll-feed
  - jekyll-remote-theme

logo: "/assets/images/logo.png"

aux_links:
  "GitHub":
    - "//github.com/ductwork/ductwork"

footer_content: "Copyright &copy; 2025 Tyler Ewing"
