title: "Ductwork Docs"
email: support@getductwork.io
description: A Ruby Pipeline Framework
baseurl: ""
url: "https://docs.getductwork.io"
github_username: zoso10

theme: just-the-docs
color_scheme: dark
plugins:
  - jekyll-feed

logo: "/assets/images/logo.png"

aux_links:
  "GitHub":
    - "//github.com/ductwork/ductwork"
