title: "Ductwork Docs"
email: support@getductwork.io
description: A Ruby Pipeline Framework
baseurl: ""
url: "https://docs.getductwork.io"
github_username: zoso10
ga_tracking: G-YH4ZQTTVJH

remote_theme: just-the-docs/just-the-docs
color_scheme: dark
plugins:
  - jekyll-feed
  - jekyll-remote-theme

logo: "/assets/images/logo.png"

mermaid:
  version: 11.12.1

callouts:
  highlight:
    color: yellow
  important:
    color: blue
  new:
    color: green
  note:
    color: purple
  warning:
    color: red


aux_links:
  "Home":
    - "https://www.getductwork.io"
  "GitHub":
    - "//github.com/ductwork/ductwork"

footer_content: "Copyright &copy; 2025-2026 Pen and Paper Solutions LLC<br>Made in Chicago, IL ❤️"

exclude: [LICENSE.txt, Gemfile, Gemfile.lock, README.md]
